language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm
before_script:
  - composer selfupdate
  - composer install
script:
  - phpunit
after_success:
  - chmod +x test/publishCoverage.sh
  - test/publishCoverage.sh
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.5
